
package nuevo_directorio.clases;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPersonaService", targetNamespace = "http://ws.jwsclase2_2_3/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPersonaService {


    /**
     * 
     * @return
     *     returns nuevo_directorio.clases.Persona
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersona", targetNamespace = "http://ws.jwsclase2_2_3/", className = "nuevo_directorio.clases.GetPersona")
    @ResponseWrapper(localName = "getPersonaResponse", targetNamespace = "http://ws.jwsclase2_2_3/", className = "nuevo_directorio.clases.GetPersonaResponse")
    @Action(input = "http://ws.jwsclase2_2_3/IPersonaService/getPersonaRequest", output = "http://ws.jwsclase2_2_3/IPersonaService/getPersonaResponse")
    public Persona getPersona();

}
