
package nuevo_directorio.clases;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "personaImpl1Service", targetNamespace = "http://ws.jwsclase2_2_3/", wsdlLocation = "http://localhost:8085/persona1Service?wsdl")
public class PersonaImpl1Service
    extends Service
{

    private final static URL PERSONAIMPL1SERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONAIMPL1SERVICE_EXCEPTION;
    private final static QName PERSONAIMPL1SERVICE_QNAME = new QName("http://ws.jwsclase2_2_3/", "personaImpl1Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/persona1Service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONAIMPL1SERVICE_WSDL_LOCATION = url;
        PERSONAIMPL1SERVICE_EXCEPTION = e;
    }

    public PersonaImpl1Service() {
        super(__getWsdlLocation(), PERSONAIMPL1SERVICE_QNAME);
    }

    public PersonaImpl1Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONAIMPL1SERVICE_QNAME, features);
    }

    public PersonaImpl1Service(URL wsdlLocation) {
        super(wsdlLocation, PERSONAIMPL1SERVICE_QNAME);
    }

    public PersonaImpl1Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONAIMPL1SERVICE_QNAME, features);
    }

    public PersonaImpl1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonaImpl1Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPersonaService
     */
    @WebEndpoint(name = "PersonaImpl1ServicePort")
    public IPersonaService getPersonaImpl1ServicePort() {
        return super.getPort(new QName("http://ws.jwsclase2_2_3/", "PersonaImpl1ServicePort"), IPersonaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPersonaService
     */
    @WebEndpoint(name = "PersonaImpl1ServicePort")
    public IPersonaService getPersonaImpl1ServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.jwsclase2_2_3/", "PersonaImpl1ServicePort"), IPersonaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONAIMPL1SERVICE_EXCEPTION!= null) {
            throw PERSONAIMPL1SERVICE_EXCEPTION;
        }
        return PERSONAIMPL1SERVICE_WSDL_LOCATION;
    }

}
